### ISSUE TITLE
How to add quora pixel and google analytics?

### ISSUE THREAD

**Issue by vinay504** [themefisher/bigspring-hugo-startup-theme#36]
I am trying to add quora pixel on this hugo theme with forestry. I am unable to do so because of less editing options available. is there any way to add quora pixel? Also i cant find any option to add google analytics.

**Comment by pnijhara** [comment]
In your `config.toml` add the following lines.
```toml
disqusShortname = "" # get your shortname form here : https://disqus.com
# google analytics
googleAnalytics = "" # example : UA-123-45
```
You can add disqus and google analytics. I am not sure about quora pixel.
